markdown:       rdiscount
pygments:       false
multiviews:     false
sass:           false
haml:           false

paginate:       5

permalink:      /:categories/:title.html
plugins:        ./_plugins

nav:
    - archive
    - blog
    - resources 

title:          Eve Kosofsky Sedgwick
feed:           /atom.xml
description:    "Eve Kosofsky Sedgwick"
    
disqus:
    id:         evesedgwick