markdown:       rdiscount
pygments:       false
multiviews:     false
sass:           false
haml:           false

permalink:      /:categories/:title.html
plugins:        ./_plugins

exclude: ["config.rb", "rakefile", "x_resources", "README", "x_includes"]

nav:
    - archive
    - blog
    - resources 

title:          Eve Kosofsky Sedgwick
feed:           /atom.xml
description:    "Eve Kosofsky Sedgwick"

posts_per_page: 5

disqus:
    id:         evesedgwick