markdown:       rdiscount
highlighter:    null
multiviews:     false
sass:
  sass_dir: assets/scss
haml:           false
permalink:      /:categories/:title.html
plugins_dir:    ./_plugins
destination:    _site

title:          Eve Kosofsky Sedgwick
feed:           /atom.xml
description:    "Eve Kosofsky Sedgwick"

nav:
    - archive
    - blog
    - commentary

category-settings:
    -   category: art
        description: ""
    -   category: teaching
        description: ""
    -   category: courses
        description: ""
    -   category: "supporting materials"
        description: ""
    -   category: conferences
        description: ""
    -   category: articles
        description: "These are uncollected publications from books, journals, and talks"
posts_per_page: 5

index_images:
    -   index1.jpg
    -   index2.jpg
    -   index3.jpg
    -   index4.jpg
    -   index5.jpg

index_image_duration: 10000
index_image_transition: slow

exclude: ["config.rb", "rakefile", "x_resources", "README", "x_includes", "x_archive", "externals", "scripts", "etc"]
