markdown:       rdiscount
pygments:       false
multiviews:     false
sass:           true
haml:           false

permalink:      /:categories/:title.html
plugins:        ./_plugins


title:          Eve Kosofsky Sedgwick
feed:           /atom.xml
description:    "Eve Kosofsky Sedgwick"
    
disqus:
    id:         evesedgwick