markdown:       rdiscount
pygments:       false
multiviews:     false
sass:           false
haml:           false

permalink: /Users/pilchard/Code/FRL/EKS/evesedgwick/_site/:title.html
base_url: file:///Users/pilchard/Code/FRL/EKS/evesedgwick

title:          Eve Kosofsky Sedgwick
feed:           /atom.xml
description:    "Initial jekyll trial by boris"

author:
    name:       boris
    email:      boris.boris@gmail.com
    
disqus:
    id:         evesedgwick

nav:
    - name:     Blog
      url:      /
    
    - name:     Portfolio
      url:      /portfolio/
    
    - name:     About
      url:      /about/
      subnav:
        - name: Contact
          url:  mailto:info@evesedgwick.com

      
copyright:
    - Design by <a href="http://bryanreedy.org">boris</a>
    - "&copy; Copyright 2011, Hal Sedgwick. All Rights Reserved."
      
css:
    - /lib/appden.css
    - /lib/syntax.css
    
js:
    - http://ajax.googleapis.com/ajax/libs/mootools/1.2.4/mootools-yui-compressed.js
    - /lib/mootools-more.js
    - /lib/appden.js
