backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "src/images"
public_folder: "/images"
collections:
  - name: "images"
    create: true
    label: "Images"
    folder: "src/_posts/work/art/images"
    slug: "{{publish_date}}-{{title}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Category", name: "category", widget: "hidden", default: "images"}
      - {label: "Type", name: "type", widget: "hidden", default: "image"}
      - {label: "Publish Date", name: "publish_date", widget: "datetime", format: "YYYY-MM-DD", time_format: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Caption Title", name: "caption-title", widget: "string"}
      - {label: "Caption", name: "caption", widget: "text"}
      - label: "Albums"
        name: "albums"
        widget: "list"
        summary: '{{fields.album}}'
        field: {label: "album", name: "album", widget: "string"}
      - label: "Detail Page"
        name: "more-link"
        widget: "string"
        default: "/images/{{slug}}"
      - label: "Image File (thumb)"
        name: "src-thumb"
        widget: "image"
        media_folder: "/src/images/archive"
        public_folder: ""
      - label: "Image File (medium)"
        name: "src-med"
        widget: "image"
        media_folder: "/src/images/archive"
        public_folder: ""
      - label: "Image File (full)"
        name: "src-full"
        widget: "image"
        media_folder: "/src/images/archive"
        public_folder: ""
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog"
    create: true
    label: "Blog"
    folder: "src/_posts/blog"
    slug: "{{publish_date}}-{{title}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Nav", name: "nav", widget: "hidden", default: "blog"}
      - {label: "Category", name: "category", widget: "hidden", default: "blog"}
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Published", name: "published", widget: "hidden", default: true}
      - {label: "Publish Date", name: "publish_date", widget: "datetime", format: "YYYY-MM-DD", time_format: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Related Images"
        name: "related-images"
        widget: "image"
        allow_multiple: true
        media_folder: "/src/images/blog"
        media_library:
          config:
              multiple: true
      - label: "Thumbnails (please resize images from above and upload with '_thumb' suffix)"
        name: "related-images-thumbs"
        widget: "image"
        allow_multiple: true
        media_folder: "/src/images/blog"
        media_library:
          config:
              multiple: true
      - {label: "Body", name: "body", widget: "markdown", required: false}