backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "src/images"
public_folder: "/images"
collections:
  - name: "blog"
    create: true
    label: "Blog"
    folder: "_posts/blog"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.md"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Nav", name: "nav", widget: "hidden", default: "blog"}
      - {label: "Category", name: "category", widget: "hidden", default: "blog"}
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Published", name: "published", widget: "boolean", default: false}
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Related Images"
        name: "related-images"
        widget: "image"
        allow_multiple: true
        media_folder: "/src/images/blog"
        media_library:
          config:
              multiple: true
      - label: "Thumbnails (please resize images from above and upload with '_thumb' suffix)"
        name: "related-images-thumbs"
        widget: "image"
        allow_multiple: true
        media_folder: "/src/images/blog"
        media_library:
          config:
              multiple: true
      - {label: "Body", name: "body", widget: "markdown"}